pipeline {
    agent any 
    tools {nodejs "node"}

    stages {
        stage('Example') {
            steps {

                sh 'npm config ls'
            }
        }    
        stage('start server'){
            steps {
                sh 'pm2 start app.js --name "application_backend" pm2 save '
            }
        } 
    }
}